FIX:fetchers:imgurfetcher title string encoding
SantiagoTorres/bg_daemon pull request #13
Opened 2016-09-20 13:56 UTC by SantiagoTorres

The title string as obtained from the imgur library doesn't encode
characters in either ascii or utf-8, but provides a Unicode object
(which I never seem to understand). This causes a crash when trying to
log a title that contains extraneous characters (as it can be seen
with the multiplication sign under https://imgur.com/6KswIQG).

We force UTF-8 encoding on the title string to avoid this issue.

2016-09-20 13:58 UTC, SantiagoTorres commented
hmm, for some reason there are other commits in this PR.. 
@ElDeveloper, I guess we should cherry pick this commit into master? other suggestions?

2016-11-26 22:26 UTC, ElDeveloper requested changes
Thanks for fixing the problem with the commits. Just a couple comments. :shipit:

2016-11-26 22:26 UTC, ElDeveloper commented on src/info.json
> +{"description": null, "author": "N/A", "section": "EarthPorn", "views": 1351, "link": "http://i.imgur.com/NVoTiPC.jpg", "title": "Trinity Alps, CA "}
Can you remove this file?

2016-11-26 22:26 UTC, ElDeveloper commented on src/bg_daemon/fetchers/imgurfetcher.py
> +            title = selected_image.title.encode("utf-8", errors='ignore')
Any chance you can add a test for this?

2017-06-07 20:25 UTC, closed without merging